### ISSUE TITLE
Reordering of compiler arguments causes wrong debug information level

### ISSUE THREAD

**Issue by EnricoB1** [icecc/icecream#424]
icecream is reordering some arguments, which causes issues when trying to build with reduced debug information. 

Tested with gcc 5.2. Building with -gsplit-dwarf and reduced debug information -g1:

`gcc -c foo.cpp -o foo.o -gsplit-dwarf -g1`

but icecream will change this to something like:

`gcc -c foo.cpp -o foo.o -g1 -gsplit-dwarf`

The result is a binary with full debug info.

**Comment by HenryMiller1** [comment]
I think this is fixed, if not re-open

**Comment by EnricoB1** [comment]
I ran the tests added in pull request #425 and the issue is not fixed. See [test run](https://travis-ci.org/EnricoB1/icecream/builds/461163347). Looks like it is fixed for the local compile, but not for remote compile. Since I can't re-open an issue closed by a collaborator, I'll have to create a new one.
